fail_on_violations: true

scss:
  enabled: true
  config_file: scss/.scss-lint.yml

javascript:
  enabled: false

eslint:
  enabled: true
  config_file: js/.eslintrc.json
  ignore_file: .houndignore

ruby:
  enabled: false
