sudo: false
dist: trusty
language: node_js
git:
  depth: 3
node_js:
  - "4"
  - "6"
before_install:
  - if [[ `npm -v` != 3* ]]; then npm install -g npm@3; fi
  - "export TRAVIS_COMMIT_MSG=\"`git log --format=%B --no-merges -n 1`\""
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[skip validator\]'; export TWBS_DO_VALIDATOR=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[skip sauce\]'; export TWBS_DO_SAUCE=$?; true
  - if [ "$TRAVIS_REPO_SLUG" = twbs-savage/bootstrap ]; then export TWBS_DO_VALIDATOR=0; fi
install:
  - bundle install --deployment --jobs=3 --retry=3
  - cp grunt/npm-shrinkwrap.json ./
  - npm install
after_success:
  - if [ "$TWBS_TEST" = sauce-js-unit ]; then grunt/upload-preview.sh; fi
cache:
  directories:
    - node_modules
    - vendor/bundle
    - "$HOME/google-cloud-sdk"
env:
  - TWBS_TEST=core
  - TWBS_TEST=validate-html
  - TWBS_TEST=sauce-js-unit
matrix:
  exclude:
    - node_js: "4"
      env: TWBS_TEST=validate-html
    - node_js: "4"
      env: TWBS_TEST=sauce-js-unit
notifications:
  slack: heybb:iz4wwosL0N0EdaX1gvgkU0NH
  webhooks:
    - http://savage.twbsapps.com/savage/travis
